# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b62e63145ed2535dd4430abfd2bee7ffb9a62850d7277e439fdc391d7f686554544e8023d6c6540896b784ed5c8cb6839c061b4c9485c647597354562b3f531

test:
  secret_key_base: adcf302a960d8e7504c86b6a4a93795849832c4135d8785617dc2461762396f99bf317d89bd641ec84c32c8b36966dd5a413c13bbab134ff969ffc9473d63452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
